package com.rahi.mhc.inotrans.fragment.fragment;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Created by MHC on 6/22/2016.
 */

/**
 * Created by MHC on 6/27/2016.
 */

public class ParseJSON {
    public static String[] ids;
    public static String[] names;
    public static String[] address;
    public static String[] address2;
//    public static String[] address3;
//    public static String[] cancle;
//    public static String[] lat;
//    public static String[] lng;
    public static String[] stopA;
    public static String[] stop1;
    public static String[] stop2;
    public static String[] stop3;
    public static String[] stop4;
    public static String[] stop5;
    public static String[] stop6;
    public static String[] stop7;
    public static String[] stop8;
    public static String[] stop9;
    public static String[] stop10;
    public static String[] stop11;
    public static String[] stop12;
    public static String[] stop13;
    public static String[] stop14;
    public static String[] stop15;
    public static String[] stop16;
    public static String[] stop17;
    public static String[] stop18;
    public static String[] stop19;
    public static String[] stop20;
    public static String[] stop21;
    public static String[] stop22;
    public static String[] stop23;
    public static String[] stop24;
    public static String[] stop25;
    public static String[] stop26;
    public static String[] stop27;
    public static String[] stop28;
    public static String[] stop29;
    public static String[] stop30;
    public static String[] stop31;
    public static String[] stop32;
    public static String[] stop33;
    public static String[] stop34;
    public static String[] stop35;
    public static String[] stop36;
    public static String[] stop37;
    public static String[] stop38;
    public static String[] stop39;
    public static String[] stop40;
    public static String[] stop41;
    public static String[] stop42;
    public static String[] stop43;
    public static String[] stop44;
    public static String[] stop45;
    public static String[] stop46;
    public static String[] stop47;
    public static String[] stop48;
    public static String[] stop49;
    public static String[] stop50;
    public static String[] stop51;
    public static String[] stop52;
    public static String[] stop53;
    public static String[] stop54;
    public static String[] stop55;
    public static String[] stop56;
    public static String[] stop57;
    public static String[] stop58;
    public static String[] stop59;
    public static String[] stop60;
    public static String[] stop61;
    public static String[] stop62;
    public static String[] stop63;
    public static String[] stop64;
    public static String[] stop65;
    public static String[] stop66;
    public static String[] stop67;
    public static String[] stop68;
    public static String[] stop69;
    public static String[] stop70;
    public static String[] stop71;
    public static String[] stop72;
    public static String[] stop73;
    public static String[] stop74;
    public static String[] stop75;
    public static String[] stop76;
    public static String[] stop77;
    public static String[] stop78;
    public static String[] stop79;
    public static String[] stop80;
    public static String[] stop81;
    public static String[] stop82;
    public static String[] stop83;
    public static String[] stop84;
    public static String[] stop85;
    public static String[] stop86;
    public static String[] stop87;
    public static String[] stop88;
    public static String[] stop89;
    public static String[] stop90;

    public static String[] time1;
    public static String[] time2;
    public static String[] time3;
    public static String[] time4;
    public static String[] time5;
    public static String[] time6;
    public static String[] time7;
    public static String[] time8;
    public static String[] time9;
    public static String[] time10;
    public static String[] time11;
    public static String[] time12;
    public static String[] time13;
    public static String[] time14;
    public static String[] time15;
    public static String[] time16;
    public static String[] time17;
    public static String[] time18;
    public static String[] time19;
    public static String[] time20;
    public static String[] time21;
    public static String[] time22;
    public static String[] time23;
    public static String[] time24;
    public static String[] time25;
    public static String[] time26;
    public static String[] time27;
    public static String[] time28;
    public static String[] time29;
    public static String[] time30;
    public static String[] time31;
    public static String[] time32;
    public static String[] time33;
    public static String[] time34;
    public static String[] time35;
    public static String[] time36;
    public static String[] time37;
    public static String[] time38;
    public static String[] time39;
    public static String[] time40;
    public static String[] time41;
    public static String[] time42;
    public static String[] time43;
    public static String[] time44;
    public static String[] time45;
    public static String[] time46;
    public static String[] time47;
    public static String[] time48;
    public static String[] time49;
    public static String[] time50;
    public static String[] time51;
    public static String[] time52;
    public static String[] time53;
    public static String[] time54;
    public static String[] time55;
    public static String[] time56;
    public static String[] time57;
    public static String[] time58;
    public static String[] time59;
    public static String[] time60;
    public static String[] time61;
    public static String[] time62;
    public static String[] time63;
    public static String[] time64;
    public static String[] time65;
    public static String[] time66;
    public static String[] time67;
    public static String[] time68;
    public static String[] time69;
    public static String[] time70;
    public static String[] time71;
    public static String[] time72;
    public static String[] time73;
    public static String[] time74;
    public static String[] time75;
    public static String[] time76;
    public static String[] time77;
    public static String[] time78;
    public static String[] time79;
    public static String[] time80;
    public static String[] time81;
    public static String[] time82;
    public static String[] time83;
    public static String[] time84;
    public static String[] time85;
    public static String[] time86;
    public static String[] time87;
    public static String[] time88;
    public static String[] time89;
    public static String[] time90;




    public static final String JSON_ARRAY = "result";
    public static final String KEY_ID = "id";
    public static final String KEY_NAME = "name";
    public static final String KEY_EMAIL = "address";
    public static final String ADDRESS2 = "address2";
//    public static final String ADDRESS3 = "address3";
//    public static final String CANCEL="cancle";
//    public static final String LATITUDE = "lat";
//    public static final String LONGITUDE="lng";
    public static final String STOPA = "stopA";
    public static final String STOP1 = "stop1";
    public static final String STOP2 = "stop2";
    public static final String STOP3 = "stop3";
    public static final String STOP4 = "stop4";
    public static final String STOP5 = "stop5";
    public static final String STOP6 = "stop6";
    public static final String STOP7="stop7";
    public static final String STOP8 = "stop8";
    public static final String STOP9="stop9";
    public static final String STOP10 = "stop10";
    public static final String STOP11 = "stop11";
    public static final String STOP12 = "stop12";
    public static final String STOP13 = "stop13";
    public static final String STOP14 = "stop14";
    public static final String STOP15 = "stop15";
    public static final String STOP16 = "stop16";
    public static final String STOP17="stop17";
    public static final String STOP18 = "stop18";
    public static final String STOP19="stop19";
    public static final String STOP20 = "stop20";
    public static final String STOP21 = "stop21";
    public static final String STOP22 = "stop22";
    public static final String STOP23 = "stop23";
    public static final String STOP24 = "stop24";
    public static final String STOP25 = "stop25";
    public static final String STOP26="stop26";
    public static final String STOP27 = "stop27";
    public static final String STOP28="stop28";
    public static final String STOP29 = "stop29";
    public static final String STOP30 = "stop30";
    public static final String STOP31 = "stop31";
    public static final String STOP32 = "stop32";
    public static final String STOP33 = "stop33";
    public static final String STOP34 = "stop34";
    public static final String STOP35 = "stop35";
    public static final String STOP36="stop36";
    public static final String STOP37 = "stop37";
    public static final String STOP38="stop38";
    public static final String STOP39 = "stop39";
    public static final String STOP40 = "stop40";
    public static final String STOP41 = "stop41";
    public static final String STOP42 = "stop42";
    public static final String STOP43 = "stop43";
    public static final String STOP44 = "stop44";
    public static final String STOP45="stop45";
    public static final String STOP46 = "stop46";
    public static final String STOP47="stop47";
    public static final String STOP48 = "stop48";
    public static final String STOP49 = "stop49";
    public static final String STOP50 = "stop50";
    public static final String STOP51 = "stop51";
    public static final String STOP52 = "stop52";
    public static final String STOP53 = "stop53";
    public static final String STOP54 = "stop54";
    public static final String STOP55="stop55";
    public static final String STOP56 = "stop56";
    public static final String STOP57="stop57";
    public static final String STOP58 = "stop58";
    public static final String STOP59 = "stop59";
    public static final String STOP60 = "stop60";
    public static final String STOP61 = "stop61";
    public static final String STOP62 = "stop62";
    public static final String STOP63 = "stop63";
    public static final String STOP64="stop64";
    public static final String STOP65 = "stop65";
    public static final String STOP66="stop66";
    public static final String STOP67 = "stop67";
    public static final String STOP68 = "stop68";
    public static final String STOP69 = "stop69";
    public static final String STOP70 = "stop70";
    public static final String STOP71 = "stop71";
    public static final String STOP72 = "stop72";
    public static final String STOP73 = "stop73";
    public static final String STOP74="stop74";
    public static final String STOP75 = "stop75";
    public static final String STOP76="stop76";
    public static final String STOP77 = "stop77";
    public static final String STOP78 = "stop78";
    public static final String STOP79 = "stop79";
    public static final String STOP80 = "stop80";
    public static final String STOP81 = "stop81";
    public static final String STOP82 = "stop82";
    public static final String STOP83="stop83";
    public static final String STOP84 = "stop84";
    public static final String STOP85="stop85";
    public static final String STOP86 = "stop86";
    public static final String STOP87 = "stop87";
    public static final String STOP88 = "stop88";
    public static final String STOP89 = "stop89";
    public static final String STOP90 = "stop90";

//
    public static final String TIME1 = "time1";
    public static final String TIME2 = "time2";
    public static final String TIME3 = "time3";
    public static final String TIME4 = "time4";
    public static final String TIME5 = "time5";
    public static final String TIME6 = "time6";
    public static final String TIME7 = "time7";
    public static final String TIME8 = "time8";
    public static final String TIME9 = "time9";
    public static final String TIME10 = "time10";
    public static final String TIME11 = "time11";
    public static final String TIME12 = "time12";
    public static final String TIME13 = "time13";
    public static final String TIME14 = "time14";
    public static final String TIME15 = "time15";
    public static final String TIME16 = "time16";
    public static final String TIME17 = "time17";
    public static final String TIME18 = "time18";
    public static final String TIME19 = "time19";
    public static final String TIME20 = "time20";
    public static final String TIME21 = "time21";
    public static final String TIME22 = "time22";
    public static final String TIME23 = "time23";
    public static final String TIME24 = "time24";
    public static final String TIME25 = "time25";
    public static final String TIME26 = "time26";
    public static final String TIME27 = "time27";
    public static final String TIME28 = "time28";
    public static final String TIME29 = "time29";
    public static final String TIME30 = "time30";
    public static final String TIME31 = "time31";
    public static final String TIME32 = "time32";
    public static final String TIME33 = "time33";
    public static final String TIME34 = "time34";
    public static final String TIME35 = "time35";
    public static final String TIME36 = "time36";
    public static final String TIME37 = "time37";
    public static final String TIME38 = "time38";
    public static final String TIME39 = "time39";
    public static final String TIME40 = "time40";
    public static final String TIME41 = "time41";
    public static final String TIME42 = "time42";
    public static final String TIME43 = "time43";
    public static final String TIME44 = "time44";
    public static final String TIME45 = "time45";
    public static final String TIME46 = "time46";
    public static final String TIME47 = "time47";
    public static final String TIME48 = "time48";
    public static final String TIME49 = "time49";
    public static final String TIME50 = "time50";
    public static final String TIME51 = "time51";
    public static final String TIME52 = "time52";
    public static final String TIME53 = "time53";
    public static final String TIME54 = "time54";
    public static final String TIME55 = "time55";
    public static final String TIME56 = "time56";
    public static final String TIME57 = "time57";
    public static final String TIME58 = "time58";
    public static final String TIME59 = "time59";
    public static final String TIME60 = "time60";
    public static final String TIME61 = "time61";
    public static final String TIME62 = "time62";
    public static final String TIME63 = "time63";
    public static final String TIME64 = "time64";
    public static final String TIME65 = "time65";
    public static final String TIME66 = "time66";
    public static final String TIME67 = "time67";
    public static final String TIME68 = "time68";
    public static final String TIME69 = "time69";
    public static final String TIME70 = "time70";
    public static final String TIME71 = "time71";
    public static final String TIME72 = "time72";
    public static final String TIME73 = "time73";
    public static final String TIME74 = "time74";
    public static final String TIME75 = "time75";
    public static final String TIME76 = "time76";
    public static final String TIME77 = "time77";
    public static final String TIME78 = "time78";
    public static final String TIME79 = "time79";
    public static final String TIME80 = "time80";
    public static final String TIME81 = "time81";
    public static final String TIME82 = "time82";
    public static final String TIME83 = "time83";
    public static final String TIME84 = "time84";
    public static final String TIME85 = "time85";
    public static final String TIME86 = "time86";
    public static final String TIME87 = "time87";
    public static final String TIME88 = "time88";
    public static final String TIME89 = "time89";
    public static final String TIME90 = "time90";







    private JSONArray users = null;

    private String json;

    public ParseJSON(String json){
        this.json = json;
    }

    protected void parseJSON(){
        JSONObject jsonObject=null;
        try {
            jsonObject = new JSONObject(json);
            users = jsonObject.getJSONArray(JSON_ARRAY);

            ids = new String[users.length()];
            names = new String[users.length()];
            address = new String[users.length()];
            address2=new String[users.length()];
//            address3=new String[users.length()];
//            cancle=new String[users.length()];
//            lat=new String[users.length()];
//            lng=new String[users.length()];
            stopA=new String[users.length()];
            stop1=new String[users.length()];
            stop2=new String[users.length()];
            stop3=new String[users.length()];
            stop4=new String[users.length()];
            stop5=new String[users.length()];
            stop6=new String[users.length()];
            stop7=new String[users.length()];
            stop8=new String[users.length()];
            stop9=new String[users.length()];
            stop10=new String[users.length()];
            stop11=new String[users.length()];
            stop12=new String[users.length()];
            stop13=new String[users.length()];
            stop14=new String[users.length()];
            stop15=new String[users.length()];
            stop16=new String[users.length()];
            stop17=new String[users.length()];
            stop18=new String[users.length()];
            stop19=new String[users.length()];
            stop20=new String[users.length()];
            stop21=new String[users.length()];
            stop22=new String[users.length()];
            stop23=new String[users.length()];
            stop24=new String[users.length()];
            stop25=new String[users.length()];
            stop26=new String[users.length()];
            stop27=new String[users.length()];
            stop28=new String[users.length()];
            stop29=new String[users.length()];
            stop30=new String[users.length()];
            stop31=new String[users.length()];
            stop32=new String[users.length()];
            stop33=new String[users.length()];
            stop34=new String[users.length()];
            stop35=new String[users.length()];
            stop36=new String[users.length()];
            stop37=new String[users.length()];
            stop38=new String[users.length()];
            stop39=new String[users.length()];
            stop40=new String[users.length()];
            stop41=new String[users.length()];
            stop42=new String[users.length()];
            stop43=new String[users.length()];
            stop44=new String[users.length()];
            stop45=new String[users.length()];
            stop46=new String[users.length()];
            stop47=new String[users.length()];
            stop48=new String[users.length()];
            stop49=new String[users.length()];
            stop50=new String[users.length()];
            stop51=new String[users.length()];
            stop52=new String[users.length()];
            stop53=new String[users.length()];
            stop54=new String[users.length()];
            stop55=new String[users.length()];
            stop56=new String[users.length()];
            stop57=new String[users.length()];
            stop58=new String[users.length()];
            stop59=new String[users.length()];
            stop60=new String[users.length()];
            stop61=new String[users.length()];
            stop62=new String[users.length()];
            stop63=new String[users.length()];
            stop64=new String[users.length()];
            stop65=new String[users.length()];
            stop66=new String[users.length()];
            stop67=new String[users.length()];
            stop68=new String[users.length()];
            stop69=new String[users.length()];
            stop70=new String[users.length()];
            stop71=new String[users.length()];
            stop72=new String[users.length()];
            stop73=new String[users.length()];
            stop74=new String[users.length()];
            stop75=new String[users.length()];
            stop76=new String[users.length()];
            stop77=new String[users.length()];
            stop78=new String[users.length()];
            stop79=new String[users.length()];
            stop80=new String[users.length()];
            stop81=new String[users.length()];
            stop82=new String[users.length()];
            stop83=new String[users.length()];
            stop84=new String[users.length()];
            stop85=new String[users.length()];
            stop86=new String[users.length()];
            stop87=new String[users.length()];
            stop88=new String[users.length()];
            stop89=new String[users.length()];
            stop90=new String[users.length()];

            time1=new String[users.length()];
            time2=new String[users.length()];
            time3=new String[users.length()];
            time4=new String[users.length()];
            time5=new String[users.length()];
            time6=new String[users.length()];
            time7=new String[users.length()];
            time8=new String[users.length()];
            time9=new String[users.length()];
            time10=new String[users.length()];
            time11=new String[users.length()];
            time12=new String[users.length()];
            time13=new String[users.length()];
            time14=new String[users.length()];
            time15=new String[users.length()];
            time16=new String[users.length()];
            time17=new String[users.length()];
            time18=new String[users.length()];
            time19=new String[users.length()];
            time20=new String[users.length()];
            time21=new String[users.length()];
            time22=new String[users.length()];
            time23=new String[users.length()];
            time24=new String[users.length()];
            time25=new String[users.length()];
            time26=new String[users.length()];
            time27=new String[users.length()];
            time28=new String[users.length()];
            time29=new String[users.length()];
            time30=new String[users.length()];
            time31=new String[users.length()];
            time32=new String[users.length()];
            time33=new String[users.length()];
            time34=new String[users.length()];
            time35=new String[users.length()];
            time36=new String[users.length()];
            time37=new String[users.length()];
            time38=new String[users.length()];
            time39=new String[users.length()];
            time40=new String[users.length()];
            time41=new String[users.length()];
            time42=new String[users.length()];
            time43=new String[users.length()];
            time44=new String[users.length()];
            time45=new String[users.length()];
            time46=new String[users.length()];
            time47=new String[users.length()];
            time48=new String[users.length()];
            time49=new String[users.length()];
            time50=new String[users.length()];
            time51=new String[users.length()];
            time52=new String[users.length()];
            time53=new String[users.length()];
            time54=new String[users.length()];
            time55=new String[users.length()];
            time56=new String[users.length()];
            time57=new String[users.length()];
            time58=new String[users.length()];
            time59=new String[users.length()];
            time60=new String[users.length()];
            time61=new String[users.length()];
            time62=new String[users.length()];
            time63=new String[users.length()];
            time64=new String[users.length()];
            time65=new String[users.length()];
            time66=new String[users.length()];
            time67=new String[users.length()];
            time68=new String[users.length()];
            time69=new String[users.length()];
            time70=new String[users.length()];
            time71=new String[users.length()];
            time72=new String[users.length()];
            time73=new String[users.length()];
            time74=new String[users.length()];
            time75=new String[users.length()];
            time76=new String[users.length()];
            time77=new String[users.length()];
            time78=new String[users.length()];
            time79=new String[users.length()];
            time80=new String[users.length()];
            time81=new String[users.length()];
            time82=new String[users.length()];
            time83=new String[users.length()];
            time84=new String[users.length()];
            time85=new String[users.length()];
            time86=new String[users.length()];
            time87=new String[users.length()];
            time88=new String[users.length()];
            time89=new String[users.length()];
            time90=new String[users.length()];

            for(int i=0;i<users.length();i++){
                JSONObject jo = users.getJSONObject(i);
                ids[i] = jo.getString(KEY_ID);
                names[i] = jo.getString(KEY_NAME);
                address[i] = jo.getString(KEY_EMAIL);
                address2[i] = jo.getString(ADDRESS2);

//                address3[i] = jo.getString(ADDRESS3);
//                cancle[i]=jo.getString(CANCEL);
////                lat[i]=jo.getString(LATITUDE);
////                lng[i]=jo.getString(LONGITUDE);

                stopA[i]=jo.getString(STOPA);
                stop1[i]=jo.getString(STOP1);
                stop2[i]=jo.getString(STOP2);
                stop3[i]=jo.getString(STOP3);
                stop4[i]=jo.getString(STOP4);
                stop5[i]=jo.getString(STOP5);
                stop6[i]=jo.getString(STOP6);
                stop7[i]=jo.getString(STOP7);
                stop8[i]=jo.getString(STOP8);
                stop9[i]=jo.getString(STOP9);
                stop10[i]=jo.getString(STOP10);
                stop11[i]=jo.getString(STOP11);
                stop12[i]=jo.getString(STOP12);
                stop13[i]=jo.getString(STOP13);
                stop14[i]=jo.getString(STOP14);
                stop15[i]=jo.getString(STOP15);
                stop16[i]=jo.getString(STOP16);
                stop17[i]=jo.getString(STOP17);
                stop18[i]=jo.getString(STOP18);
                stop19[i]=jo.getString(STOP19);
                stop20[i]=jo.getString(STOP20);
                stop21[i]=jo.getString(STOP21);
                stop22[i]=jo.getString(STOP22);
                stop23[i]=jo.getString(STOP23);
                stop24[i]=jo.getString(STOP24);
                stop25[i]=jo.getString(STOP22);
                stop26[i]=jo.getString(STOP26);
                stop27[i]=jo.getString(STOP27);
                stop28[i]=jo.getString(STOP28);
                stop29[i]=jo.getString(STOP29);
                stop30[i]=jo.getString(STOP30);
                stop31[i]=jo.getString(STOP31);
                stop32[i]=jo.getString(STOP32);
                stop33[i]=jo.getString(STOP33);
                stop34[i]=jo.getString(STOP34);
                stop35[i]=jo.getString(STOP35);
                stop36[i]=jo.getString(STOP36);
                stop37[i]=jo.getString(STOP37);
                stop38[i]=jo.getString(STOP38);
                stop39[i]=jo.getString(STOP39);
                stop40[i]=jo.getString(STOP40);
                stop41[i]=jo.getString(STOP41);
                stop42[i]=jo.getString(STOP42);
                stop43[i]=jo.getString(STOP43);
                stop44[i]=jo.getString(STOP44);
                stop45[i]=jo.getString(STOP45);
                stop46[i]=jo.getString(STOP46);
                stop47[i]=jo.getString(STOP47);
                stop48[i]=jo.getString(STOP48);
                stop49[i]=jo.getString(STOP49);
                stop50[i]=jo.getString(STOP50);
                stop51[i]=jo.getString(STOP51);
                stop52[i]=jo.getString(STOP52);
                stop53[i]=jo.getString(STOP53);
                stop54[i]=jo.getString(STOP54);
                stop55[i]=jo.getString(STOP55);
                stop56[i]=jo.getString(STOP56);
                stop57[i]=jo.getString(STOP57);
                stop58[i]=jo.getString(STOP58);
                stop59[i]=jo.getString(STOP59);
                stop60[i]=jo.getString(STOP60);
                stop61[i]=jo.getString(STOP61);
                stop62[i]=jo.getString(STOP62);
                stop63[i]=jo.getString(STOP63);
                stop64[i]=jo.getString(STOP64);
                stop65[i]=jo.getString(STOP65);
                stop66[i]=jo.getString(STOP66);
                stop67[i]=jo.getString(STOP67);
                stop68[i]=jo.getString(STOP68);
                stop69[i]=jo.getString(STOP69);
                stop70[i]=jo.getString(STOP70);
                stop71[i]=jo.getString(STOP71);
                stop72[i]=jo.getString(STOP72);
                stop73[i]=jo.getString(STOP73);
                stop74[i]=jo.getString(STOP74);
                stop75[i]=jo.getString(STOP75);
                stop76[i]=jo.getString(STOP76);
                stop77[i]=jo.getString(STOP77);
                stop78[i]=jo.getString(STOP78);
                stop79[i]=jo.getString(STOP79);
                stop80[i]=jo.getString(STOP80);
                stop81[i]=jo.getString(STOP81);
                stop82[i]=jo.getString(STOP82);
                stop83[i]=jo.getString(STOP83);
                stop84[i]=jo.getString(STOP84);
                stop85[i]=jo.getString(STOP85);
                stop86[i]=jo.getString(STOP86);
                stop87[i]=jo.getString(STOP87);
                stop88[i]=jo.getString(STOP88);
                stop89[i]=jo.getString(STOP89);
                stop90[i]=jo.getString(STOP90);

                time1[i]=jo.getString(TIME1);
                time2[i]=jo.getString(TIME2);
                time3[i]=jo.getString(TIME3);
                time4[i]=jo.getString(TIME4);
                time5[i]=jo.getString(TIME5);
                time6[i]=jo.getString(TIME6);
                time7[i]=jo.getString(TIME7);
                time8[i]=jo.getString(TIME8);
                time9[i]=jo.getString(TIME9);
                time10[i]=jo.getString(TIME10);
                time11[i]=jo.getString(TIME11);
                time12[i]=jo.getString(TIME12);
                time13[i]=jo.getString(TIME13);
                time14[i]=jo.getString(TIME14);
                time15[i]=jo.getString(TIME15);
                time16[i]=jo.getString(TIME16);
                time17[i]=jo.getString(TIME17);
                time18[i]=jo.getString(TIME18);
                time19[i]=jo.getString(TIME19);
                time20[i]=jo.getString(TIME20);
                time21[i]=jo.getString(TIME21);
                time22[i]=jo.getString(TIME22);
                time23[i]=jo.getString(TIME23);
                time24[i]=jo.getString(TIME24);
                time25[i]=jo.getString(TIME25);
                time26[i]=jo.getString(TIME26);
                time27[i]=jo.getString(TIME27);
                time28[i]=jo.getString(TIME28);
                time29[i]=jo.getString(TIME29);
                time30[i]=jo.getString(TIME30);
                time31[i]=jo.getString(TIME31);
                time32[i]=jo.getString(TIME32);
                time33[i]=jo.getString(TIME33);
                time34[i]=jo.getString(TIME34);
                time35[i]=jo.getString(TIME35);
                time36[i]=jo.getString(TIME36);
                time37[i]=jo.getString(TIME37);
                time38[i]=jo.getString(TIME38);
                time39[i]=jo.getString(TIME39);
                time40[i]=jo.getString(TIME40);
                time41[i]=jo.getString(TIME41);
                time42[i]=jo.getString(TIME42);
                time43[i]=jo.getString(TIME43);
                time44[i]=jo.getString(TIME44);
                time45[i]=jo.getString(TIME45);
                time46[i]=jo.getString(TIME46);
                time47[i]=jo.getString(TIME47);
                time48[i]=jo.getString(TIME48);
                time49[i]=jo.getString(TIME49);
                time50[i]=jo.getString(TIME50);
                time51[i]=jo.getString(TIME51);
                time52[i]=jo.getString(TIME52);
                time53[i]=jo.getString(TIME53);
                time54[i]=jo.getString(TIME54);
                time55[i]=jo.getString(TIME55);
                time56[i]=jo.getString(TIME56);
                time57[i]=jo.getString(TIME57);
                time58[i]=jo.getString(TIME58);
                time59[i]=jo.getString(TIME59);
                time60[i]=jo.getString(TIME60);
                time61[i]=jo.getString(TIME61);
                time62[i]=jo.getString(TIME62);
                time63[i]=jo.getString(TIME63);
                time64[i]=jo.getString(TIME64);
                time65[i]=jo.getString(TIME65);
                time66[i]=jo.getString(TIME66);
                time67[i]=jo.getString(TIME67);
                time68[i]=jo.getString(TIME68);
                time69[i]=jo.getString(TIME69);
                time70[i]=jo.getString(TIME70);
                time71[i]=jo.getString(TIME71);
                time72[i]=jo.getString(TIME72);
                time73[i]=jo.getString(TIME73);
                time74[i]=jo.getString(TIME74);
                time75[i]=jo.getString(TIME75);
                time76[i]=jo.getString(TIME76);
                time77[i]=jo.getString(TIME77);
                time78[i]=jo.getString(TIME78);
                time79[i]=jo.getString(TIME79);
                time80[i]=jo.getString(TIME80);
                time81[i]=jo.getString(TIME81);
                time82[i]=jo.getString(TIME82);
                time83[i]=jo.getString(TIME83);
                time84[i]=jo.getString(TIME84);
                time85[i]=jo.getString(TIME85);
                time86[i]=jo.getString(TIME86);
                time87[i]=jo.getString(TIME87);
                time88[i]=jo.getString(TIME88);
                time89[i]=jo.getString(TIME89);
                time90[i]=jo.getString(TIME90);

            }
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

}
